### ISSUE TITLE
{ current: true } query option not working (aria-current)

### ISSUE THREAD

**Issue by christemple** [testing-library/dom-testing-library#1047] opened 2021-10-05 09:50 UTC
- `@testing-library/dom` version: 8.7.2
- Testing Framework and version: jest 27.2.1
  
- DOM Environment: jsdom 16.6.0
  

### Relevant code or config:

Open the tests tab on this sandbox:
https://codesandbox.io/s/react-testing-library-demo-forked-chm9j?file=/src/__tests__/hello.js

### What you did:

Tried using the new `{ current: true }` option for filtering by `aria-current` attributes.

### What happened:

It keeps returning multiple elements, as if it's ignoring the `{ current }` option

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-chm9j?file=/src/__tests__/hello.js

### Problem description:

`getByRole('button', { current: true })` keeps returning multiple elements (when there is only 1 current element), it's as if the `{ current }` option just gets ignored.

### Suggested solution:

I actually forked the repo and tried writing the test to reproduce the problem, **however when I wrote the test to verify this scenario it passes**
I don't know what the difference is between the queries in the repo and the queries that are consumed via the package, but it's almost as if the query being consumed via the package doesn't have support for the `{.current: true }` option?

**Comment by eps1lon** [comment] 2021-10-05 09:54
In your codesandbox you're still on version 9.3.

Can you reproduce the bug with the latest versions of `@testing-library/*`? Also try to run the test locally. Codesandbox had some issues in the past with its test environment.

**Comment by MatanBobi** [comment] 2022-01-06 21:16
![image](https://user-images.githubusercontent.com/12711091/148453186-59c91dd6-170b-42b1-9fda-85182e69a591.png)

This test is passing for my locally and since no comment was given here for more than 3 months, I'm closing this one.

@christemple, if you're still experiencing issues with this, comment here or feel free to reopen the issue.
Thanks and have a great year!

**Closed by MatanBobi** 2022-01-06 21:16 UTC
Labels: needs more information

**Comment by oskarols** [comment] 2022-08-17 14:55
For anyone else stumbling into this and using Vue 2.x, this issue is most likely due to `@testing-library/dom` being in version 7.x which doesn't support the `aria-current` attribute. Unfortunately it will not outright fail, it just won't use the `current` option.

**Comment by afontcu** [comment] 2022-08-17 15:00
> For anyone else stumbling into this and using Vue 2.x, this issue is most likely due to `@testing-library/dom` being in version 7.x which doesn't support the `aria-current` attribute. Unfortunately it will not outright fail, it just won't use the `current` option.

true that @oskarols! happy to review a PR (detaching from https://github.com/testing-library/vue-testing-library/tree/v5.8.3, which targets Vue 2) that bumps `@testing-library/dom` to v8 :)
