### ISSUE TITLE
Shouldn't `ByRole` query find an element with `display: none` if I'm using hidden: true?

### ISSUE THREAD

**Issue by felipecesr** [testing-library/dom-testing-library#1333] opened 2024-08-13 19:44 UTC
I want to get an element with `display: none` style using the bellow query:

```js
// Component
 <button style={{ display: 'none' }}>Button</button>

// Testing
screen.getByRole('button', { name: /button/i, hidden: true })
```

`getByRole` can't find the element. But it works if I use `getByText` like that:

```js
screen.getByText(/button/i)
```

Is this the expected behavior? And why?

**Comment by MatanBobi** [comment] 2024-08-14 07:31
Hi @felipecesr, thanks for opening this.
As you can see in the output of the test, hidden attributes have no accessible name:
```
Here are the available roles:

  button:

  Name "":
  <button
    style="display: none;"
  />
```
This is following the [spec](https://www.w3.org/TR/accname-1.2/#computation-steps), the problem is browsers sometimes don't follow the spec and that's why you can see an accessible name in Chrome for example.
I'm closing this as works by design since we're spec compliant here.

**Closed by MatanBobi** 2024-08-14 07:31 UTC
