### ISSUE TITLE
Querying hidden dialog by name fails

### ISSUE THREAD

**Issue by axelboc** [testing-library/dom-testing-library#913] opened 2021-03-19 10:21 UTC
- `@testing-library/dom` version: 7.30.0
- Testing Framework and version:
  - Jest: 26.6.0
- DOM Environment:
  - JSDOM: 16.4.0

### Relevant code or config:

```js
export default () => (
  <>
    <div role="dialog" aria-label="Visible" />
    <div role="dialog" aria-label="Hidden" hidden />
  </>
);
```

### What you did:

```js
// This passes
expect(getByRole("dialog", { name: "Visible" })).toBeVisible();
expect(queryByRole("dialog", { name: "Hidden" })).toBeNull();
expect(queryAllByRole("dialog", { hidden: true })).toHaveLength(2);

// This fails
expect(getByRole("dialog", { name: "Hidden", hidden: true })).not.toBeVisible();
```

### What happened:

```
Unable to find an element with the role "dialog" and name "Hidden"
```

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-imxvc?file=/src/hello.js

### Problem description:

`getByRole` and the like don't seem to be able to find hidden dialogs by name.

**Comment by eps1lon** [comment] 2021-03-19 13:43
Duplicate of https://github.com/testing-library/dom-testing-library/issues/846

**Closed by eps1lon** 2021-03-19 13:43 UTC
