### ISSUE TITLE
userEvent.click(screen.getAll*) produces an ambiguous error

### ISSUE THREAD

**Issue by juanca** [testing-library/dom-testing-library#892] opened 2021-02-17 00:04 UTC
- `@testing-library/dom` version: @testing-library/dom@7.29.4
- Testing Framework and version: Karma
  - karma@4.4.1
  - jasmine@3.3.1
- DOM Environment: Chrome Version 88.0.4324.182 (Official Build) (x86_64)

Relevant code or config

Repro sandbox: https://codesandbox.io/s/react-testing-library-demo-forked-u4lcu?file=/src/__tests__/hello.js

What you did:

I ran a test and tried to click the result of `screen.getAllByLabelText`. 

What happened:

Running the test produces something like:

![image](https://user-images.githubusercontent.com/841084/108136666-49657a00-706f-11eb-8a36-d117c527258d.png)

where the element in question is an array:

![image](https://user-images.githubusercontent.com/841084/108136688-5a15f000-706f-11eb-9853-1b404cd1d721.png)

Problem description:

The thrown error is a bit ambiguous -- there is room for improvement. 

Suggested solution:

I would assume that `userEvent` methods would error on having multiple elements -- where the error text would be a bit more direct. I am not sure if a user can interact with more than 1 element at a time.

**Comment by timdeschryver** [comment] 2021-02-18 10:24
Seems like a good idea to me 👍

**Comment by MatanBobi** [comment] 2021-02-18 12:59
Sounds good.. Though I'm thinking the code for this should be inside `user-event` and not `dom-testing-library`..
Do you agree so I'll move this one to `user-event`'s repo?

**Comment by timdeschryver** [comment] 2021-02-18 14:56
Isn't this also the case with `fireEvent`? 
If we fix it there, it will also be fixed for `user-event` because they use `fireEvent`?

**Comment by MatanBobi** [comment] 2021-02-18 15:08
> Isn't this also the case with `fireEvent`?
> If we fix it there, it will also be fixed for `user-event` because they use `fireEvent`?

You're right I wasn't thinking about it, I just reproduced it with `fireEvent` also.
So this should be fixed here..

**Comment by juanca** [comment] 2021-02-19 21:43
Unless someone gets to it by end of Sunday, I'll probably give it a stab.

**Comment by juanca** [comment] 2021-02-28 19:43
I never did specify _which_ Sunday. Lemme know how that looks, it seemed suspiciously _too_ straight-forward ;)

**Closed** 2021-03-07 10:41 UTC
