### ISSUE TITLE
getByRole incorrectly thinking element is hidden

### ISSUE THREAD

**Issue by dawnlunacy** [testing-library/dom-testing-library#931] opened 2021-04-15 00:51 UTC
- `@testing-library/dom` version: 7.29.0
- Testing Framework and version: @testing-library/react@11.2.2
  
- DOM Environment: jsdom@16.4.0
  
- Node Version: v15.14.0

### Relevant code or config:
Simplified example:
Rendered a component that after a certain event fires, renders something like the following:

```html
<div>
  <span>Some text</span>
  <a href="/">link</a>
</div>
```

### What you did:
1. We (@wdoug and I )rendered the component with react testing library.
2. Fired the event that triggered a rerender
3. In the test we had: 
```js
await screen.findByText('Some text`);
const link = screen.getByRole('link', { name: 'link' });
expect(link).toBeVisible();
```

### What happened:
The test gave us an error like: `unable to find accessible element with role link and name 'link'`

We used the debugger to step through and understand what was happening. We found that the dom testing library ended up filtering out the link because it thought it was hidden. Specifically, [this line](https://github.com/testing-library/dom-testing-library/blob/3b585160f5e19febc9daf62266e36410aff13b94/src/role-helpers.js#L55) returned true for the root of the component, so the `WeakMap` cache was saying that it was hidden. When running `window.getComputedStyle(currentElement).visibility` on that element, however, it returned `visible` and everything suggested that it should be visible.

After finding this we did confirm that the following test code passed:
```js
await screen.findByText('Some text`);
const link = screen.getByRole('link', { name: 'link', hidden: true });
expect(link).toBeVisible();
```
However, `hidden: true` shouldn't be required

### Reproduction:
We do not have a minimal reproducible setup for this bug currently but wanted to start the conversation.

### Problem description:

See Above. This seems like a bug in the library because as far as we could tell, the component was visible. 

### Suggested solution:
🤷‍♂️ 🤷‍♀️

**Comment by eps1lon** [comment] 2021-04-15 07:22
Thanks for the report.

> We do not have a minimal reproducible setup for this bug currently but wanted to start the conversation.

Without this I can only guess which might be counterproductive. Note that `inaccessible` is not just CSS `visbibility` but `display` and `aria-hidden`. You can find more information in the [documentation of the `hidden` option](https://testing-library.com/docs/queries/byrole/#hidden). So you might want to check if all these other conditions are satisfied as well.

**Comment by eps1lon** [comment] 2021-06-02 12:03
Closing since no reproduction was provided.

**Closed by eps1lon** 2021-06-02 12:03 UTC
Labels: needs investigation
