### ISSUE TITLE
CI failing with op_mob browserslist error

### ISSUE THREAD

**Issue by cmorten** [testing-library/dom-testing-library#1242] opened 2023-06-25 11:25 UTC
- `@testing-library/dom` version: latest
- Testing Framework and version: N/A
- DOM Environment: N/A
  

### Relevant code or config:

N/A

### What you did:

Run `npm run setup -s` locally or in CI.

### What happened:

```console
$ kcd-scripts build  --no-ts-defs --ignore "**/__tests__/**,**/__node_tests__/**,**/__mocks__/**" && kcd-scripts build --no-ts-defs --bundle --no-clean
Error [BrowserslistError]: Unknown version 64 of op_mob
```

### Reproduction:

`npm run setup -s`

### Problem description:

op_mob 64 is not supported, as noted in https://github.com/testing-library/dom-testing-library/pull/1170#issuecomment-1595300619.

### Suggested solution:

Move to use `op_mob 73` provided it doesn’t result in a breaking change, otherwise a different config to unblock build.

**Comment by MatanBobi** [comment] 2023-06-25 11:26
Hi @cmorten :)
I already pushed a fix to your PR for this one, I saw this before and didn't get a chance to fix it.

**Comment by eps1lon** [comment] 2023-06-26 20:51
Please fix this in a different PR so that we can better bisect/revert later.

**Comment by MatanBobi** [comment] 2023-06-28 06:50
I'm re-opening this because what we have at the moment is a workaround (we've pinned the version) :)

**Comment by MatanBobi** [comment] 2023-07-20 07:11
This issue is more urgent than we thought because our workaround fails our node 14 CI because npm 6 doesn't support `overrides`.

**Comment by nickmccurdy** [comment] 2023-09-10 04:23
So #1255 should fix this, right?

**Comment by MatanBobi** [comment] 2023-09-10 04:26
> So #1255 should fix this, right?

It should fix the failure but it's still a workaround. We should probably update the browsers we support at some point I guess.

**Comment by nickmccurdy** [comment] 2023-09-10 04:32
That's just a matter of updating `browserslist`, right? Since we're doing a major anyway, let's include a fix then.

**Comment by MatanBobi** [comment] 2023-09-10 06:27
> That's just a matter of updating `browserslist`, right? Since we're doing a major anyway, let's include a fix then.

Yes, that's a really good point. I'll do it and create a PR to the alpha branch.

**Comment by nickmccurdy** [comment] 2023-09-12 21:19
This issue seems to only reproduce with Node 16, which is no longer officially supported. Please upgrade to Node 18+ and npm 7+ (if used) and then reinstall dependencies.

We can leave this open for visibility, but it will be fixed in DTL 10. You can also install the `alpha` channel now, but you'll still need to upgrade Node and npm (if used).

**Comment by eps1lon** [comment] 2023-09-16 08:47
> It should fix the failure but it's still a workaround. We should probably update the browsers we support at some point I guess.

It's the other way around. https://github.com/testing-library/dom-testing-library/pull/1243 did fix it permanently. Bumping op_mob is the workaround since it'll break again eventually. We'd have to constantly bump browserslist and ship majors to keep CI green. Locking it is the permanent fix that should stay. 

That doesn't mean we can't update browserslist in the next major though.

**Comment by eps1lon** [comment] 2023-09-16 08:56
Problem is that we use the bundled NPM version and the one bundled with Node.js 14 doesn't support overrides. Pinning NPM version which makes sense anyway. We don't want to test different NPM versions. Just Node.js versions.

**Comment by MatanBobi** [comment] 2023-09-17 07:25
> > It should fix the failure but it's still a workaround. We should probably update the browsers we support at some point I guess.
> 
> It's the other way around. #1243 did fix it permanently. Bumping op_mob is the workaround since it'll break again eventually. We'd have to constantly bump browserslist and ship majors to keep CI green. Locking it is the permanent fix that should stay.
> 
> That doesn't mean we can't update browserslist in the next major though.

I understand what you're saying and that's definitely a valid point. If that's the case, shouldn't this be pinned in `kcd-scripts` which defines them?
When using `overrides` it feels like we're solving the issue just for us.
I can update https://github.com/testing-library/dom-testing-library/pull/1257 to use `defaults` and update the `overrides` dependencies. That will be good once #1262 will be merged.

**Closed** 2023-09-17 15:10 UTC

**Comment by eps1lon** [comment] 2023-09-17 15:14
If kcd-scripts can pin `browserslist`, I'm all for it.
