### ISSUE TITLE
supported event.movementX

### ISSUE THREAD

**Issue by AntonS86** [testing-library/dom-testing-library#1087] opened 2022-01-14 08:49 UTC
hi please add property support event.movementX

---test code---
```ts
fireEvent.mouseMove(el, { clientX: 100, movementX: 3, screenX: 5 });
```
---component code---

```ts
onMouseMove = (e: MouseEvent): void => {
   console.log(e.clientX, e.movementX, e.screenX);
   if (e.movementX) {
     this.props.onResize(e.movementX);
   }
};
```

---console output---
100 undefined 5

**Comment by MatanBobi** [comment] 2022-01-14 11:15
Hi @AntonS86!
Next time we will appreciate if you'll open the issue based on our template and add a reproduction via a repo or codesandbox.
For the specific use-case you're describing, are you using JSDOM as your testing environment?
Because it seems like [JSDOM have an issue ](https://github.com/jsdom/jsdom/issues/3209) with `movementX` and since we're only creating the event, if JSDOM is omitting that, we have no control on the actual event being triggered.

**Comment by eps1lon** [comment] 2022-08-09 13:13
Closing in favor of https://github.com/jsdom/jsdom/issues/3209

**Closed by eps1lon** 2022-08-09 13:13 UTC
Labels: jsdom
