### ISSUE TITLE
Github actions - tests pass but execution fails on Process completed with exit code 1.

### ISSUE THREAD

**Issue by gnesher** [testing-library/dom-testing-library#1292] opened 2024-02-25 17:04 UTC
- `@testing-library/dom` version: 7.31.2
- Testing Framework and version: @testing-library/jest-dom 5.11.4
- Jest 26.0.15
- DOM Environment:
jsdom 27.4.4

### Relevant code or config:
N/A

### What you did:
Runnig test suit passes fine locally and all tests are reported to have passed successfully on github actions i.e.
```
Test Suites: 25 passed, 25 total
Tests:       163 passed, 163 total
Snapshots:   85 passed, 85 total
Time:        515.31 s
Ran all test suites matching /^.*\/[C][\w-]*\.test/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
But tests still fail with exit code 1

### Problem description:

Tests pass successfully but the test fails on Github Actions with error code 1 while reporting all tests passed 

### Suggested solution:

The last time we encountered this issue we solved it by ensuring that waitFor is limited to 1 except (but while this isn't recommended according to https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#having-multiple-assertions-in-a-single-waitfor-callback - it shouldn't cause this

**Comment by MatanBobi** [comment] 2024-02-25 20:20
Hi @gnesher! Thanks for opening this one.
The last version of DTL 7 was released almost 3 years ago, we're not supporting that anymore and a lot has changed since then.
Any chance you can upgrade the libraries you're using to see if it still reproduces?
Thanks.

**Comment by MatanBobi** [comment] 2024-06-07 07:07
I'm closing this as no reproduction was provided.
If anyone is experiencing this and can provide a reproduction, we'll be happy to help :)

**Closed by MatanBobi** 2024-06-07 07:07 UTC

**Comment by sjpknight** [comment] 2024-12-08 00:10
I'm experiencing this. 

2024-12-08T00:03:07.2049575Z    PASS  Tests\Unit\ExampleTest
2024-12-08T00:03:07.2079489Z   ✓ that true is true
2024-12-08T00:03:07.6539289Z 
2024-12-08T00:03:07.6539728Z    PASS  Tests\Feature\EmailTest
2024-12-08T00:03:07.6554146Z   ✓ list emails route                                                    0.40s  
2024-12-08T00:03:07.6566468Z   ✓ create email route                                                   0.04s  
2024-12-08T00:03:07.7300975Z 
2024-12-08T00:03:07.7301510Z    PASS  Tests\Feature\WebRoutesTest
2024-12-08T00:03:07.7314238Z   ✓ root route                                                           0.03s  
2024-12-08T00:03:07.7326491Z   ✓ emails route                                                         0.02s  
2024-12-08T00:03:07.7338351Z   ✓ campaigns route                                                      0.03s  
2024-12-08T00:03:07.7340453Z 
2024-12-08T00:03:07.7343783Z   Tests:    6 passed (12 assertions)
2024-12-08T00:03:07.7344584Z   Duration: 0.57s
2024-12-08T00:03:07.7344962Z 
2024-12-08T00:03:07.7550815Z ##[error]Process completed with exit code 1.

I've attached the logs. Any input welcomed. It's very frustrating!
[GAlogs.txt](https://github.com/user-attachments/files/18050285/GAlogs.txt)
