### ISSUE TITLE
fireEvent doesn't work in pointer event

### ISSUE THREAD

**Issue by gwBear1** [testing-library/dom-testing-library#1291] opened 2024-02-23 08:20 UTC
- `@testing-library/dom` version: `^9.3.4`
- Testing Framework and version: jest - `^26.6.3`
  
- DOM Environment: jest
  

### Relevant code or config:

```js
None
```

### What you did:
fireEvent does not fire the pointer event such as `onpointerup`, `onpointerdown`

### What happened:
fireEvent does not fire the pointer event such as `onpointerup`, `onpointerdown`

### Reproduction:
- in the browser
```javascript
const tempMouse = document.createElement('div')
tempMouse.onmouseup = () => {
  console.log('run1')
}
tempMouse.dispatchEvent(new MouseEvent('mouseup'))
// 'run' will be shown

const tempPointer = document.createElement('div')
tempPointer.onpointerup = () => {
  console.log('run2')
}
tempPointer.dispatchEvent(new PointerEvent('pointerup'))
// 'run' will be shown
```
<img width="446" alt="스크린샷 2024-02-23 오후 5 16 39" src="https://github.com/testing-library/dom-testing-library/assets/138835573/2a8decfb-9d75-4cb6-8caf-6367b3d3205e">

- However in the jest environment
```javascript
const tempMouse = document.createElement('div')
tempMouse.onmouseup = () => {
  console.log('run1')
}
fireEvent.mouseUp(tempMouse);
// 'run' be shown.

const tempPointer = document.createElement('div')
tempPointer.onpointerup = () => {
  console.log('run2')
}
fireEvent.pointerUp(tempPointer);
// 'run' will not be shown.
```
<img width="494" alt="스크린샷 2024-02-23 오후 5 18 04" src="https://github.com/testing-library/dom-testing-library/assets/138835573/5a54f23e-7b8b-4dff-8d18-1acbf273ae13">

### Suggested solution:
Should work pointer event same as browser.

**Comment by jlp-craigmorten** [comment] 2024-03-15 11:20
See also:

- https://github.com/testing-library/react-testing-library/issues/317
- https://github.com/jsdom/jsdom/issues/2527

The issue is upstream in JSDom not supporting the event properly. There is somewhat of a workaround in the comments https://github.com/jsdom/jsdom/issues/2527#issuecomment-1488182727 (though with likely caveats).

**Comment by MatanBobi** [comment] 2024-03-16 05:31
Thanks for finding this one @jlp-craigmorten :)
I'm closing this issue in favor of the JSDOM one.

**Closed by MatanBobi** 2024-03-16 05:31 UTC
