### ISSUE TITLE
Should we add a script load event ? 

### ISSUE THREAD

**Issue by JulienKode** [testing-library/dom-testing-library#498] opened 2020-03-24 17:12 UTC
Thank you for this nice library 

Currently it's possible to trigger a `load` event on a image:
Example:
```javascript
const { getByTestId, debug } = render(<Stuff/>);

fireEvent.load(getByTestId('my-stuff'));

expect(stuff).toHaveBeenCalledWith(true);
```

But is there any way to do that with `script` ?
Should we implement it here https://github.com/testing-library/dom-testing-library/blob/6c4486c5c290aac515f103314428a9ab2e2873fb/src/__tests__/events.js#L109

**Comment by kentcdodds** [comment] 2020-05-10 01:54
What would it take to support this? It's it not already supported?

**Comment by gertsonderby** [comment] 2020-05-18 11:51
It works for me with this test:
```js
test('can set load event handler', () => {
    const handler = jest.fn();
    // This component creates a script with a usdeEffect hook
    render(<TestComponent options={{ onLoad: handler }} src="https://example.com/test.js" />);
    const script = document.head.querySelector('script')!;
    expect(handler).not.toHaveBeenCalled();
    fireEvent.load(script);
    return waitFor(() => expect(handler).toHaveBeenCalled());
});
```

**Comment by gertsonderby** [comment] 2020-05-18 12:01
I'm digging a little. This test fails (using react testing lib):
```js
test('can load a script', () => {
    const handler = jest.fn();
    render(<script onLoad={handler} src="https://example.com/test.js" />);
    const script = document.querySelector('script');
    expect(handler).not.toHaveBeenCalled();
    fireEvent.load(script);
    expect(handler).toHaveBeenCalled(); // Was not called.
});
```
But this one succeeds:
```js
test('can load a script', () => {
    const handler = jest.fn();
    render(<script src="https://example.com/test.js" />);
    const script = document.querySelector('script');
    script.onload = handler;
    expect(handler).not.toHaveBeenCalled();
    fireEvent.load(script);
    expect(handler).toHaveBeenCalled();
});
```
As you can see, the only difference is that the handler is set indirectly. So there may be an issue wrt. setting the handler?

**Comment by JulienKode** [comment] 2020-05-26 11:05
@gertsonderby I didn't notice that if I set the `onload` directly in the script it work

**Comment by kentcdodds** [comment] 2020-05-26 17:11
Sounds like this may be an issue with React's support of `onLoad`?

**Comment by gertsonderby** [comment] 2020-05-26 17:23
Possibly. Although I don't think they're all too interested in supporting script tags like that, it seems out of scope.

Personally, I would add them to `<head>` with a`useEffect` hook instead of rendering them directly.

**Comment by sibelius** [comment] 2022-02-17 17:53
is this a workaround to test jQuery onload like this code ?

```jsx
$(() => {
   console.log('testing lib onload jquery')
})
```

**Comment by danascheider** [comment] 2022-06-26 23:11
Hi everybody, I'm commenting in hopes of saving somebody the full week of frustration I had with this. I was testing a `useEffect` hook using [`renderHook`](https://github.com/testing-library/react-testing-library/blob/c80809a956b0b9f3289c4a6fa8b5e8cc72d6ef6d/src/pure.js#L221-L247). The hook adds a `<script>` tag to the document head in a `useEffect` hook, like @gertsonderby suggested. I had the following test for my hook:

```js
it('calls the success callback with the current user', async () => {
  const params = { onSuccess, clientId, staySignedIn: true }

  // This hook calls the function that adds the script to the document
  renderHook(() => useGoogleLogin(params))

  const script = document.querySelector('script')
  fireEvent.load(script)

  await waitFor(() => expect(onSuccess).toHaveBeenCalled())
})
```

I was getting the same issue - if I set `onSuccess` to be the `onload` callback within the test itself (`script.onload = onSuccess`), it worked, and it failed if I didn't do that explicitly.

This is the function called in the hook:

```js
const loadGapiScript = (document, src, onLoad, onError) => {
  const script = document.getElementsByTagName('script')[0]

  let js = document.createElement('script')
  js.id = 'google-auth'
  js.src = src
  js.async = true
  js.defer = true

  js.onerror = onError
  js.onload = onLoad

  if (script && script.parentNode) {
    script.parentNode.insertBefore(js, script)
  } else {
    document.head.appendChild(js)
  }
}
```

The following two lines turned out to be the problem:

```js
js.onerror = onError
js.onload = onLoad
```

Changing them to this ended up solving the issue:

```js
js.onerror = e => onError(e)
js.onload = e => onLoad(e)
```

So, to use the original example, this should work:

```js
render(<script onLoad={e => handler(e)} src='https://example.com/test.js' />)
```

Unfortunately I'm not sure why this solved my problem, but it did 🤷‍♀️ If anybody knows why this would be I'd love to know,.

**Comment by eps1lon** [comment] 2022-07-09 08:51
Firing load events at scripts is supported in `@testing-library/dom`. If you find issues specific to `@testing-library/dom` please provide a minimal repro (e.g. no rendering with React) and open a new issue.

For people looking for support in React: Scripts will not execute if rendered via React so it's expected that there's no `load` event: https://codesandbox.io/s/react-script-does-not-work-the-way-you-think-it-does-stc66c?file=/src/index.js. Check how your component behaves in a browser first before writing tests that replay the expected behavior.

So you need to manually insert the script into the DOM e.g. like in https://github.com/testing-library/dom-testing-library/issues/498#issuecomment-1166673388

**Closed by eps1lon** 2022-07-09 08:51 UTC
