### ISSUE TITLE
getByLabelText stopped returning div associated with label via the "for" attribute

### ISSUE THREAD

**Issue by ipap360** [testing-library/dom-testing-library#716] opened 2020-07-25 16:57 UTC
- `@testing-library/dom` version: > 7.21.1
- Testing Framework and version: jest 25.5.4
- DOM Environment: jsdom v16
- Node.JS: v12.18.1

### Relevant code or config:

![form-control](https://user-images.githubusercontent.com/11017666/88461659-4e799680-ce9d-11ea-9cd6-53ef794443d1.PNG)

### What you did:

getByLabelText("Data product:")

### What happened:

TestingLibraryElementError: Found a label with the text of: Data product:, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-v8wzb?file=/src/hello.js
Tried to reproduce this here but I couldn't; it seems to be working. Interestingly, this happened to us as well when the sub-dependency testing-library/dom that testing-library/react depends on was stuck to a lower version.

### Problem description:

Semantically the "for" attribute associates labels with form controls (input, select etc) however in practice, we use several more advanced controls, often wrapped into div containers (e.g. react-select). 

Until v7.21.1, testing-library/dom supported this "non-standard" use of the label which is convenient.

### Suggested solution:

If making this more semantically accurate is a design choice by the authors, it is of course understandable. But we'll need to change the code for these advanced components to use "aria-labelledby" instead (which creates some inconvenience)

Thanks in advance

**Comment by timdeschryver** [comment] 2020-07-25 18:03
This seems like a duplicate of #714 ?

**Comment by kentcdodds** [comment] 2020-07-25 18:05
Perhaps we could add a more helpful error message for this?

**Comment by ipap360** [comment] 2020-07-25 18:10
Apologies, I thought I searched the entire internet and missed one of the most recent issues!

**Comment by kentcdodds** [comment] 2020-07-25 18:34
No worries. It's a tricky one to Google for. Would you like to help by adding a more helpful error for this case?

**Comment by ipap360** [comment] 2020-07-26 20:41
Sure, it'd be my pleasure!
I presume that it should cover labels associated with any non-labellable elements and not just with divs, right?

**Comment by kentcdodds** [comment] 2020-07-26 20:42
Yep 👍

**Comment by eps1lon** [comment] 2020-07-29 16:50
Closed in #720

**Closed by eps1lon** 2020-07-29 16:50 UTC
