### ISSUE TITLE
`fireEvent.keyPress` should change the value of input

### ISSUE THREAD

**Issue by dehghani-mehdi** [testing-library/dom-testing-library#1106] opened 2022-02-17 07:17 UTC
Related issue #1104 and #1105, which is closed without any good reason.

KeyPress means there is a value/character entered by the user, so why RTL doesn't change the value of the input?

I don't care about the implementation details, as RTL doesn't, KeyPress cause a change in the input value, so I think `fireEvent.keyPress` doesn't implement correctly.

**Comment by timdeschryver** [comment] 2022-02-17 09:48
@dehghani-mehdi creating new issues without additional information isn't helpful for both parties.
`keyPress` doesn't change the value, you can verify this in the browser by sending the keypress event to an input.
I'm going to close this issue, and I hope you don't create a new issue for it.

Again, if you need help to test something, join the discord server.
We're using GitHub issues to track bugs, and new features, this case is not a bug but the desired behavior (as we've mentioned in the previous issues).

**Closed by timdeschryver** 2022-02-17 09:48 UTC

**Comment by dehghani-mehdi** [comment] 2022-02-17 09:55
I think you are a label, called `needs more information`, use that instead of closing the issue!

Neither creating a new issue nor does closing the issue based on your personal opinion doesn't help.
