### ISSUE TITLE
runWithExpensiveErrorDiagnosticsDisabled doesn't await

### ISSUE THREAD

**Issue by berkeleybross** [testing-library/dom-testing-library#922] opened 2021-03-26 17:13 UTC
### Problem description:

I was diagnosing a separate issue with waitFor, and I noticed that runWithExpensiveErrorDiagnosticsDisabled is called but it is probably a no-op as it currently works. I have not played around with it or proven it to be true, just thought I'd raise it and see if anyone else thinks it may be a PERF issue (since  config._disableExpensiveErrorDiagnostics will only be true up until the first await statement)

### Relevant code or config:

https://github.com/testing-library/dom-testing-library/blob/f7b5c33c44632fba1579cb44f9f175be1ec46087/src/config.ts#L45

```js
export function runWithExpensiveErrorDiagnosticsDisabled<T>(
  callback: Callback<T>,
) {
  try {
    config._disableExpensiveErrorDiagnostics = true
    return callback()
  } finally {
    config._disableExpensiveErrorDiagnostics = false
  }
}
```

### Suggested solution:

```js
export async function runWithExpensiveErrorDiagnosticsDisabled<T>(
  callback: Callback<T>,
) {
  try {
    config._disableExpensiveErrorDiagnostics = true
    return await callback()
  } finally {
    config._disableExpensiveErrorDiagnostics = false
  }
}
```

**Comment by eps1lon** [comment] 2021-03-27 09:16
Please follow the issue template and provide a complete reproduction. Or include a test that is currently failing. Then we can discuss the implementation.

**Comment by eps1lon** [comment] 2021-06-02 12:04
Closing since no reproduction was provided.

**Closed by eps1lon** 2021-06-02 12:04 UTC
Labels: needs investigation

**Comment by codingstar** [comment] 2021-07-09 04:06
I run into the same problem, @eps1lon you can see https://github.com/kentcdodds/testing-library-fake-timers to find a reproduction

**Comment by eps1lon** [comment] 2021-07-09 07:17
> I run into the same problem, @eps1lon you can see [kentcdodds/testing-library-fake-timers](https://github.com/kentcdodds/testing-library-fake-timers) to find a reproduction

Does this still reproduce with `@testing-library/dom@^8.0.0`?
