### ISSUE TITLE
jest run reports "A worker process has failed to exit gracefully ..."

### ISSUE THREAD

**Issue by deej-split** [testing-library/dom-testing-library#524] opened 2020-04-11 01:33 UTC
- `DOM Testing Library` version: 7.2.1
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 6.13.6

### Relevant code or config:

```js
require('@testing-library/dom');
```

### What you did:

See above.

### What happened:

Jest (?) is reporting the warning `A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.`  at the end of a test run

### Reproduction:

Probably pretty hard.  See below.

### Problem description:

The problem is that when we `require('@testing-library/dom');`. (even if we never call `configure()` or any other RTL code) at the end of the test run of 3500 tests we get the above warning.  Trying to subdivide the tests to find the "offending test", makes the problem go away.  So, it isn't directly due to some misbehaving test.

Interestingly, if we use `require('@testing-library/react');` and do not directly import `.../dom` we don't see the problem.

I'm not seriously expecting that you can fix this given the paucity of information I have to offer.  And given that we're on React 15, node 10 (though current Jest) it is entirely possible that this is a result of some older version of things that doesn't happen on newer configurations.  Instead, I'm filing this mainly to let you know this is happening, and to leave a record to allow others to know that someone else has seen this problem.

(the workaround appears to just be to not do any configuration of `@testing-library/dom` :-)

**Comment by alexkrolick** [comment] 2020-04-11 07:17
👋 Deej

This is tricky. Importing DTL/index is synchronous, so it shouldn't really do anything that causes Promises or timeouts to leak... I assume your tried `Try running with --runInBand --detectOpenHandles to find leaks.` and it didn't yield any useful info?

The only kind of suspicious thing I can think of is that importing `screen` could maintain a reference to `document.body` that is tied to the JSDOM instance that was present when it was created. This was added in [v6.11.0](https://github.com/testing-library/dom-testing-library/compare/v6.10.1...v6.11.0).

**Comment by deej-split** [comment] 2020-04-13 16:20
@alexkrolick 👋 

Yes, I should have mentioned I did try with the runInBand and detectOpenHandles.  And "of course" the problem went away when I did that.

And the @testing-library/dom we're getting is 7.2.1

🤷
Again, not asking for a fix, just recording that it happens.

**Comment by SarthakJha** [comment] 2020-07-27 15:10
is the command suppose to be jest --runInBand --detectOpenHandles

**Comment by deej-split** [comment] 2020-07-27 16:14
@SarthakJha I think so.  Why do you ask?

**Comment by favs-sama** [comment] 2020-08-03 10:20
I am able to reproduce permanently in one of my tests, mine has something to do with a mocked function that is used with the await js keyword

**Comment by deej-split** [comment] 2020-08-03 15:48
@favs-sama I assume it is too complex to extricate that out into a repeatable simple test case?

**Comment by rmcsharry** [comment] 2020-08-10 08:29
```
Node v12.14.1
Angular 9.1
Jest 25.2.7
```

We also see this message.

`jest --runInBand --detectOpenHandles` does not yield anything.

Is there some way to identify which tests might be leaking?

**Comment by nickmccurdy** [comment] 2020-08-21 07:23
You could try only running specific test files until you can isolate which ones are causing issues with open handles. If it's many of them, you should check your setup scripts and test utilities.

**Comment by omgoshjosh** [comment] 2020-09-21 17:48
so i only see this when i run the whole suite. in my test files, there are maybe 5 directories that contain all tests and running each one like `jest dir1` and `jest dir2` yields no message, but running the full suite with simple `jest` does show the message. but when i run it with detectOpenHandles, the message goes away. am i going crazy?

**Comment by deej-split** [comment] 2020-09-21 18:10
@omgoshjosh Not going crazy (well, maybe you are, that's independent of this ;-) ). That's exactly what I see too.  I spent some time at one point pruning down the set of tests, hoping to isolate "the one bad test" causing this.  but, as I recall eventually the problem seemed more a function of number of tests and it doesn't seem tied to any individual test in any obvious way.

**Comment by omgoshjosh** [comment] 2020-09-21 18:45
yes and even when i run a large subset, i can get the error to appear sometimes and disappear other times.

**Comment by tonystaark** [comment] 2020-10-07 04:34
I am running only one test file and it throws this error.  No idea why it happened

**Comment by deej-split** [comment] 2020-10-07 04:38
@tonystaark if it is a single test and it is repeatable, is it something you could share in some way?  Might help the maintainer to hunt it down.

**Comment by jensbodal** [comment] 2020-10-28 23:09
I see this error in a test package for backend code (e.g. doesn't involve react, this library, or the dom)

So this should probably be reported to jest

**Comment by yvele** [comment] 2020-11-05 11:31
This error suddenly appears today after having updated dependencies (no semver major updates) 🤔 

```txt
Node.js v12.19.0
jest 26.6.3
```

If I rollback to previous dependency version I don't longer have the error 🤔

**Comment by marcosvega91** [comment] 2020-11-05 11:47
Could be a regression of #801 ? @kentcdodds

**Comment by shrpne** [comment] 2020-11-05 15:54
I can confirm. I have the same issue on `jest`+`jest-circus` 26.6.3
26.5.3 works fine for me

**Comment by kentcdodds** [comment] 2020-11-05 18:05
Possibly, I'm not sure though. cc @romain-trotard

**Comment by yvele** [comment] 2020-11-06 08:25
Are you all running test using a Mac? If so it may be related to https://github.com/facebook/jest/issues/10777 and fsevent bug https://github.com/fsevents/fsevents/issues/345 that has just been fixed 🤔

**Comment by seancwalsh** [comment] 2020-11-06 11:19
I presume there's another issue people are referring to here, but just incase someone finds themselves reading. For me deleting node modules and the yarn lock file then re installing dependencies resolved this issue 🤷🏻‍♂️

**Comment by osedoe** [comment] 2020-11-06 17:42
In line with @seancwalsh, I can confirm that doing a clean install and bumping Jest to 26.6.3 seems to fix it.

https://github.com/facebook/jest/releases/tag/v26.6.3

**Comment by kentcdodds** [comment] 2020-11-06 18:12
Sounds like this is unrelated to Testing Library, so I'm going to close it :) Thanks everyone!

**Closed by kentcdodds** 2020-11-06 18:12 UTC

**Comment by luistak** [comment] 2020-12-23 18:12
In my scenario, there were two different histories In the same test

I fixed this issue by changing every jest `history` creation  from `createBrowserHistory` to `createMemoryHistory`

**Comment by FahmyChaabane** [comment] 2021-03-11 20:17
I did face the same thing in 2021,
A node v14.15.5 project. i did use jest 26.6.3 for my testing.
Had only passed the --detectOpenHandles option, and Voila, the warning was gone.

**Comment by rogeliosamuel621** [comment] 2021-04-18 00:34
2 things that help me to troubleshoot this issue

- make sure that you don't have any `setTimeOut` function
- Use done() callback where you think is the issue

My problem was that I was trying to close an expressjs server but took time.

```js
// this was not working
  afterAll((done) => {
    await server.close();
    done();
  });

//this worked
  afterAll((done) => {
    server.close(() => {
      done();
    });
  });
```

To solve the problems that are about timers, use `jest.useFakeTimers();`
```
describe('my suit of tests', () => {
    jest.useFakeTimers();
    // my tests..
})
```

**Comment by stephmajor** [comment] 2021-04-24 00:47
I can get this all the time when using a utility package I use for my work (jest 26.6.3, node 12.20)

isolated test:

```
import { convertHtmlToDelta } from 'node-quill-converter';

afterAll(() => {
    // tried to get rid of the offending module to no avail
    jest.resetModules();
    jest.resetModuleRegistry();
    delete require.cache[require.resolve('node-quill-converter')];
});

describe('convertHtmlToDelta', () => {
    const htmlContent = `
        <!DOCTYPE html>
        <html>
            <body>
                some text
            </body>
        </html>
    `;

    it('converts HTML to quill delta JSON', () => {
        const delta = convertHtmlToDelta(htmlContent);
        expect(delta).toMatchInlineSnapshot(`
            s {
              "ops": Array [
                Object {
                  "insert": "some text",
                },
              ],
            }
        `);
    });
});
```

**Comment by parzhitsky** [comment] 2021-05-19 09:00
For anybody who gets here through search results, – try to check if you are _really_ not forgetting to `.close()` all your connections with databases, etc, – something that jest cannot figure out to close on its own. In my case, this was exactly that.

**Comment by skrenes** [comment] 2021-06-19 02:40
Thanks @parzhitsky! It turns out I needed this for proper shutdown of the pg-promise resources:
```javascript
afterAll(() => {
  db.$pool.end();
});
```

**Comment by nmpribeiro** [comment] 2021-12-02 08:47
I also saw this with my tests... hunted down the specific file, isolated the test and... used "setTimeout" to construct the rendered comp. Figuring exactly the piece of code is really hard, and I assumed it was probably due to some Promise deep inside my component tree (really big ... 😥).
`
-    "jest": "^27.3.1",
+    "jest": "^27.4.2",
`
And now I don't see the issue anymore... though I am really curious to see what changed between 27.3 and 27.4 now.

**Comment by axiac** [comment] 2022-07-08 17:26
When `jest` is executed with option `--detectOpenHandles` or `--runInBand` the message disappears.

**Comment by WalterWeidner** [comment] 2022-08-05 14:17
We ran into this issue in our tests and it turned out to be someone using `waitFor()` in their test. 

Ultimately it seems like the cause is that RTL is configured to timeout tests at 1s (per [this documentation](https://testing-library.com/docs/dom-testing-library/api-async)) and Jest is configured to kill its workers after 500ms. Changing our default RTL config to timeout at less than 500ms fixed things for us.

**Comment by ahayes91** [comment] 2022-08-05 15:53
> Ultimately, it seems like the cause is that RTL is configured to timeout tests at 1s (per [this documentation](https://testing-library.com/docs/dom-testing-library/api-async)) and Jest is configured to kill its workers after 500ms (see [their source](https://github.com/facebook/jest/blob/24e0472ac41ea03cdd89ffaea8c5f410ecf6054f/packages/jest-worker/src/base/BaseWorkerPool.ts#L19)). Changing our default RTL config to timeout at less than 500ms fixed things for us.

Yikes, I didn't realise that - I've had performance issues with RTL tests in the past (e.g. https://github.com/testing-library/dom-testing-library/issues/820) where one of the solutions was to up the jest timeouts and asyncUtilTimeout a bit. Going that low would probably cause a lot of tests to fail for us 🤔

**Comment by leneti** [comment] 2023-05-06 14:39
I ran into this same issue when console.log() was called in a tested component. After mocking console.log() in my jest.setup file, the warning went away, but I'm not sure what's happening.

```
// jest.setup.ts

global.console = {
  ...global.console,
  log: jest.fn().mockName("mock.console.log"),
};
```

```
// jest.config.ts

...
setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
...
```

**Comment by vitaly-t** [comment] 2025-09-19 12:10
> Thanks [@parzhitsky](https://github.com/parzhitsky)! It turns out I needed this for proper shutdown of the pg-promise resources:
> 
> afterAll(() => {
>   db.$pool. End();
> });

You should just pass option `allowExitOnIdle: true` when creating pg-promise Database instance.
