### ISSUE TITLE
waitForElementToBeRemoved throws error when passed an element

### ISSUE THREAD

**Issue by zaicevas** [testing-library/dom-testing-library#993] opened 2021-07-10 18:08 UTC
### What you did:

Wrote a test with `await waitForElementToBeRemoved(screen.queryByText("Loading..."));`

### What happened:

Got a failing test `Timed out in waitForElementToBeRemoved.`

### Reproduction:

https://codesandbox.io/s/testing-userevent-the-proper-way-forked-mx356?file=/src/App.test.js

### Problem description:

As far as I can see, `waitForElementToBeRemoved` accepts either a function or an element. I'd expect those to work identically.
However, `await waitForElementToBeRemoved(() => screen.queryByText("Loading..."));` works, while `await waitForElementToBeRemoved(screen.queryByText("Loading..."));` does not work.

**Comment by AriPerkkio** [comment] 2021-07-11 07:25
The element passed to `waitForElementToBeRemoved` is not unmounted. [React is only replacing its `textContent`](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-dom/src/client/setTextContent.js#L12-L35) or the text node inside it. 

Refactor code to make current test pass:
```diff
  return (
    <>
-      {isLoading && "Loading..."}
+      {isLoading && (<div>Loading...</div>)}
      <div>{title}</div>
    </>
  );
```
Now the element will actually unmount. 

When passing a callback to `waitForElementToBeRemoved` it is called repeatedly until it throws. That's why the other solution is currently passing the test.

**Comment by zaicevas** [comment] 2021-07-11 08:43
> The element passed to `waitForElementToBeRemoved` is not unmounted. [React is only replacing its `textContent`](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-dom/src/client/setTextContent.js#L12-L35) or the text node inside it.
> 
> Refactor code to make current test pass:
> 
> ```diff
>   return (
>     <>
> -      {isLoading && "Loading..."}
> +      {isLoading && (<div>Loading...</div>)}
>       <div>{title}</div>
>     </>
>   );
> ```
> 
> Now the element will actually unmount.
> 
> When passing a callback to `waitForElementToBeRemoved` it is called repeatedly until it throws. That's why the other solution is currently passing the test.

Wow, what an interesting reason 😮It makes sense, but now the problem seems that React's implementation details are 'spilled' into dom-testing-library API. In other words, developers need to account for such cases when thinking about whether to pass a function or an element to `waitForElementToBeRemoved`. 
2 alternatives come to my mind:

- Make an eslint rule that would force passing a function
- Disallow passing an element. That seems difficult because it'd be a breaking change

However, I am thinking purely from React's perspective and I am not sure if the second option would block any legit use cases 🤷 What do you think?

**Comment by AriPerkkio** [comment] 2021-07-21 06:43
> seems that React's implementation details are 'spilled' into dom-testing-library API

That's true. Making assertions on `HTMLElement`s could be considered as testing implementation details when you are really interested in the text user is seeing. Sure there are other valid use cases for testing actual `HTMLElement` unmounts. 

Enforcing this by ESLint rule could work but it would likely flag multiple false positives. 

Maybe the error message of `waitForElementToBeRemoved` could be improved too. Initial `textContent` of the element could be saved and compared after assertion failed. Error message could indicate the `textContent` changed but element did not unmount, and recommend to pass callback instead of element.

Instead of:
```
await waitForElementToBeRemoved(screen.queryByText("Loading..."));

Timed out in waitForElementToBeRemoved.

<div>Fetched</div>
```

Indicate textContent change:
```
await waitForElementToBeRemoved(screen.queryByText("Loading..."));

Timed out in waitForElementToBeRemoved. 
The text content of element did change from "Loading..." to "Fetched". 
Element did not unmount. Consider passing callback instead of an element.

<div>Fetched</div>
```

**Comment by zaicevas** [comment] 2021-07-24 14:56
Makes sense to me!

**Comment by eps1lon** [comment] 2021-08-25 09:15
Closing since this is expected behavior. The element isn't removed but it's original query is no longer matching. 

You probably want to `waitFor` `screen.queryByText("Loading...")` no longer returning an element.

**Closed by eps1lon** 2021-08-25 09:15 UTC
