### ISSUE TITLE
waitFor error "MutationObserver is not a constructor" with latest version

### ISSUE THREAD

**Issue by TransmissionsDev** [testing-library/dom-testing-library#477] opened 2020-03-13 04:18 UTC
- `DOM Testing Library` version: **Using React Testing Lib Version: ^10.0.0**
- `node` version: v12.13.1
- `npm` (or `yarn`) version: 6.13.7

### Relevant code or config:

```js
await waitFor(() => {
    expect(submitButton).toHaveAttribute("aria-disabled", "false");
  });
```

### What you did:

I'm using the new React-Testing-Library version and trying to fix my tests that use `waitFor`, but it I am getting a MutationObserver error that is preventing my tests from passing.

_**I'm using the built in CRA react-scripts test command to run my tests**_

### What happened:

```
    TypeError: MutationObserver is not a constructor

      146 | 
      147 |   // Wait until the picture is UPLOADED and the disabled attribute is REMOVEaD
    > 148 |   await waitFor(() => {
          |         ^
      149 |     expect(submitButton).toHaveAttribute("aria-disabled", "false");
      150 |   });
      151 | 

      at node_modules/@testing-library/dom/dist/wait-for.js:32:22
      at waitFor (node_modules/@testing-library/dom/dist/wait-for.js:25:10)
      at node_modules/@testing-library/dom/dist/wait-for.js:64:54
      at node_modules/@testing-library/react/dist/pure.js:51:22
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21887:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at asyncAct (node_modules/@testing-library/react/dist/act-compat.js:118:12)
      at Object.asyncWrapper (node_modules/@testing-library/react/dist/pure.js:50:35)
      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:64:35)
      at Object.<anonymous> (src/components/NewSpotForm.test.js:148:9)
```

**Comment by TransmissionsDev** [comment] 2020-03-13 04:57
This may be an issue with `react-scripts` having an old version of jsdom (14.1.0)?

**Comment by eps1lon** [comment] 2020-03-13 06:21
@TransmissionsDev Please include the exact version of `react-scripts` or describe your test setup. [jsdom 14 should have MutationObserver](https://github.com/jsdom/jsdom/releases/tag/13.2.0)

**Comment by flaviendelangle** [comment] 2020-03-13 07:55
`Same issue here with `jsdom` `11.5.1`
I manually installed the last version of `jsdom` (`16+`) but still had the error.

**Comment by eps1lon** [comment] 2020-03-13 08:00
> Same issue here with jsdom 11.5.1I manually installed the last version ofjsdom (16+`) but still had the error.

@flaviendelangle  On jsdom 11 this is expected. You need to make sure your testing environment is using the proper version. For example in jest you need jest-environment-jsdom-sixteen (or what it's called). This is best asked on [spectrum.chat](https://spectrum.chat/testing-library/) or StackOverflow though.

**Comment by bartlomiejzuber** [comment] 2020-03-13 08:27
Had the same issue(latest CRA) and can confirm that this fixes it:
```yarn add jest-environment-jsdom-sixteen --dev```

and then set it via `env` cli param

```
"scripts": {
   ...
   "test": "react-scripts test --env=jest-environment-jsdom-sixteen",
   ...
}
```

**Comment by kentcdodds** [comment] 2020-03-13 13:18
Sorry about this trouble. For some reason I thought CRA had the latest Jest. I'd there already an issue over there about upgrading?

**Comment by eps1lon** [comment] 2020-03-13 13:21
> Sorry about this trouble. For some reason I thought CRA had the latest Jest. I'd there already an issue over there about upgrading?

The problem is that latest `react-scripts` depends on `jest@24` not `jest@latest` (25). `jest@24` still uses `jsdom@11` by default. `MutationObserver` got added in `jsdom@13`.

**Comment by ambroseus** [comment] 2020-03-13 13:52
@kentcdodds 
> Sorry about this trouble. For some reason I thought CRA had the latest Jest. Is there already an issue over there about upgrading?
yes :) https://github.com/facebook/create-react-app/issues/8361
PR: https://github.com/facebook/create-react-app/pull/8362

**Comment by kentcdodds** [comment] 2020-03-13 13:55
For folks who don't want to use `jest-environment-jsdom-sixteen` (for whatever reason), you can also include a MutationObserver shim yourself. I've updated [the release notes](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0).

**Comment by TransmissionsDev** [comment] 2020-03-13 14:27
@kentcdodds So the solution here is to get CRA to upgrade their version of Jest? That's unfortunate, I hope we can get some quick progress with them.

**Comment by kentcdodds** [comment] 2020-03-13 14:30
There are three options listed in the release notes. So waiting is not your only option.

**Comment by kentcdodds** [comment] 2020-03-13 14:31
That said there's nothing more we can do in this repository so I'm going to close this issue.

Thank you to everyone here who contributed to the discussion and helped to improve the release notes.

**Closed by kentcdodds** 2020-03-13 14:31 UTC

**Comment by selena-mallet** [comment] 2020-04-16 08:58
this fix : https://github.com/testing-library/dom-testing-library/issues/477#issuecomment-598606649
works also with jest:
"scripts": {
   ...
"test": "jest --maxWorkers=1 --env=jest-environment-jsdom-sixteen",
 ...
}

**Comment by SandroMiguel** [comment] 2020-04-22 09:05
In my case updating Jest to v25.4.0 was enough (I'm not using CRA).

**Comment by kentr** [comment] 2020-05-08 17:54
Putting some notes about this are in the docs could save a lot of time & digging.

I got to the testing library from [React's Test Utilities page](https://reactjs.org/docs/test-utils.html), and then dove into the [Testing Library Example](https://testing-library.com/docs/react-testing-library/intro), which doesn't work without upgrading `@testing-library/react` and adding `jest-environment-jsdom-sixteen`.

**Comment by kentcdodds** [comment] 2020-05-08 20:36
Maybe putting a note about it on this page would be fine: https://testing-library.com/docs/dom-testing-library/api-async

**Comment by vadimshvetsov** [comment] 2020-05-11 13:24
How to make it working in the codesandbox? There is no window object and workaround with `MutationObserver` is not applicable. Also setting `react-scripts test --env=jest-environment-jsdom-sixteen` doesn't help.

https://codesandbox.io/s/field-eokex?file=/src/__tests__/hello.js

**Comment by kentcdodds** [comment] 2020-05-13 21:50
It works in codesandbox actually: https://codesandbox.io/s/zen-paper-wdfcu?file=/src/__tests__/index.js:539-595

I'm guessing there's something else wrong with your example.

**Comment by vadimshvetsov** [comment] 2020-05-14 00:05
@kentcdodds thanks, looks like there is a problem within my code or `react-hook-form`, but can't find out where. I've set a MutationObserver polyfill like in release notes of `@testing-library/dom`, but it doesn't works. Anyway I won't someone will spend a time on it, it's not very important issue, I've just `spyOn` `console.error` to suppress an act warning there

**Comment by przemuh** [comment] 2020-05-15 11:28
Maybe it would be helpful for someone...

In my case even updating to the latest jest 26.x didn't solve the problem. That was because we used to use `enzyme` with `jest-enzyme` package (we have not migrated all spec to testing-lib yet).

The problem is that the latest `jest-enzyme` package has dependency on `jest-environement-jsdom` in old version 24.9.0 🤦 

```
yarn why jest-environment-jsdom
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "jest-environment-jsdom"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jest-environment-jsdom@24.9.0"
info Reasons this module exists
   - "jest-enzyme#jest-environment-enzyme" depends on it
   - Hoisted from "jest-enzyme#jest-environment-enzyme#jest-environment-jsdom"
info Disk size without dependencies: "1.95MB"
info Disk size with unique dependencies: "8.34MB"
info Disk size with transitive dependencies: "32.69MB"
info Number of shared dependencies: 121
=> Found "jest-config#jest-environment-jsdom@26.0.1"
info This module exists because "jest#@jest#core#jest-config" depends on it.
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "6.41MB"
info Disk size with transitive dependencies: "30.77MB"
info Number of shared dependencies: 121
✨  Done in 1.69s.
```

So...the fix was about setting the proper resolution in package.json

```
"resolutions": {
     "jest-environment-jsdom": "^26.0.1"
}
```

**Comment by stonecrafter** [comment] 2020-07-08 08:02
I get this error when running `react-scripts test --env=jest-environment-jsdom-sixteen` .... anybody else?

```
Cannot find module '@babel/compat-data/plugin-bugfixes' (While processing: "[path/to/my/project]/node_modules/react-scripts/node_modules/babel-preset-react-app/index.js")

at Object.<anonymous> (node_modules/react-scripts/node_modules/@babel/preset-env/lib/plugins-compat-data.js:10:46)
```

Haven't found anyone else write about having this issue (or fixing it)

**Comment by neomib** [comment] 2020-09-14 14:46
For me, it was `jest-cli` that had an old version of jsdom. So first I run `npm ls jsdom` and then upgraded the libraries that I saw were using an old version of jsdom.

**Comment by jonbwalker** [comment] 2020-09-23 18:33
> For me, it was `jest-cli` that had an old version of jsdom. So first I run `npm ls jsdom` and then upgraded the libraries that I saw were using an old version of jsdom.

This worked for me! I had `jest v26` installed and `jest-junit v5` installed. Even though `jest 26` has `jsdom 16`, it was using the `jsdom` from `jest-junit` which had `jsdom 11`!

updating `jest-junit` to latest (v11) fixed the issue.

Thanks for the hint @neomib! 💯 

![Screen Shot 2020-09-23 at 11 26 26 AM](https://user-images.githubusercontent.com/6462827/94054091-03daa480-fd90-11ea-8814-a392a97efec9.png)

**Comment by richardwan** [comment] 2020-09-25 22:07
> For folks who don't want to use `jest-environment-jsdom-sixteen` (for whatever reason), you can also include a MutationObserver shim yourself. I've updated [the release notes](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0).



> For folks who don't want to use `jest-environment-jsdom-sixteen` (for whatever reason), you can also include a MutationObserver shim yourself. I've updated [the release notes](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0).

which solution did you use in this example? https://github.com/kentcdodds/react-testing-library-examples

**Comment by totaland** [comment] 2020-09-28 23:22
Hi @kentcdodds, 

There seems to be a timeout error when you fire the await waitForElementToBeRemoved twice. 

So the app I built has 3 stages when I click on a button I fire that waitForElementToBeRemoved and assert the new layout. This new layout will also has a next button. I click on that button and fire that waitForElementToBeRemoved. This time it didn't work and will have the timeout error for waitForElementToBeRemoved. 

How do I fix that?

**Comment by ajfranzoia** [comment] 2020-11-03 16:41
If you're using Webstom and you're tests are still failing, install the package as specified in https://github.com/testing-library/dom-testing-library/issues/477#issuecomment-598606649 and try adding `--env=jest-environment-jsdom-sixteen` to the Jest run configuration template.
