### ISSUE TITLE
Forms changed to Divs and not present in Role calls

### ISSUE THREAD

**Issue by rbrisita** [testing-library/dom-testing-library#738] opened 2020-08-12 22:31 UTC
- `@testing-library/dom` version: @testing-library/dom@6.16.0
- Testing Framework and version: jest@24.9.0
  
- DOM Environment: @testing-library/jest-dom@4.2.4
  

### Relevant code or config:

```js
import { getRoles } from '@testing-library/dom';

test("test form", () => {
  const div = document.createElement("div");

  div.innerHTML = `
    <form>
      <label for="first_name">
        First Name:
        <input id="first_name" name="first_name" type="text" />
      </label>
      <button type="submit">Submit</button>
    </form>
  `;

  console.log(getRoles(div)); // no form found, changed to div
});
```

### What you did:

Write a test to find an accessible element of form to assert its existence.

### What happened:

It seems that the testing library internally changes semantic HTML into generic divs.
Any Role based call will fail with:

`Unable to find an accessible element with the role "form"`

* getRoles
* getByRole

### Reproduction:

https://codesandbox.io/s/react-testing-library-demo-forked-emfob

### Problem description:

It is a problem because removing semantic HTML hinders ARIA testing.

### Suggested solution:

Don't convert semantic HTML to generic HTML. As of now, one can get around this by adding either:

* `role="form"`
* `aria-label="Form's purpose"`

But this approach is redundant (especially the former) since the semantic HTML tag of 'form' is a landmark role.

**Comment by eps1lon** [comment] 2020-08-12 22:54
The current behavior follows the spec: [A `<form>` without a name does not have the `form` role](https://www.w3.org/TR/html-aam-1.0/#details-id-42). Duplicate of #474

> But this approach is redundant (especially the former) since the semantic HTML tag of 'form' is a landmark role.

We don't implement querying abstract roles (e.g. `landmark`).

**Closed by eps1lon** 2020-08-12 22:54 UTC

**Comment by rbrisita** [comment] 2020-08-12 23:48
Thanks for the clarity.
