### ISSUE TITLE
queryByRole tests break after updating to 8.11.2

### ISSUE THREAD

**Issue by szamanr** [testing-library/dom-testing-library#1107] opened 2022-02-21 13:36 UTC
- `@testing-library/dom` version: 8.11.2
- Testing Framework and version: jest 27.5.1
- DOM Environment: no custom changes, i guess whatever comes with jest 27?

### Relevant code or config:

this test passes in 8.11.1 but fails in 8.11.2:

```ts
const parent = screen.getByRole("button", {
  name: new RegExp(mockParent[1].name),
});
const childName = new RegExp(mockParent[1].children[1].name);

expect(
  screen.getByRole("button", {
    name: childName,
  })
).toBeInTheDocument();

userEvent.click(parent);

expect(
  screen.queryByRole("button", {
    name: childName,
  })
).not.toBeInTheDocument();
```

### What you did:

automatic batch package upgrade broke a few tests. i was able to pinpoint it to this package and version 8.11.2 specifically.

### What happened:

```
Error: expect(element).not.toBeInTheDocument()

expected document not to contain element, found <div class="...">...</div> instead


    at Object.<anonymous> (/my/project/path/src/module/path/ComponentName.test.tsx:169:9)
    at Promise.then.completed (/my/project/path/node_modules/jest-circus/build/utils.js:391:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/my/project/path/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/my/project/path/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/my/project/path/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/my/project/path/node_modules/jest-circus/build/run.js:66:9)
    at run (/my/project/path/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/my/project/path/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/my/project/path/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/my/project/path/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/my/project/path/node_modules/jest-runner/build/runTest.js:475:34)
    at TestRunner.runTests (/my/project/path/node_modules/jest-runner/build/index.js:101:12)
    at TestScheduler.scheduleTests (/my/project/path/node_modules/@jest/core/build/TestScheduler.js:333:13)
    at runJest (/my/project/path/node_modules/@jest/core/build/runJest.js:404:19)
    at _run10000 (/my/project/path/node_modules/@jest/core/build/cli/index.js:320:7)
    at runCLI (/my/project/path/node_modules/@jest/core/build/cli/index.js:173:3)
    at Object.run (/my/project/path/node_modules/jest-cli/build/cli/index.js:155:37)

```

**Comment by MatanBobi** [comment] 2022-02-21 13:40
Hi @szamanr, thanks for taking the time to file this one.
It will be quite difficult for us to try and investigate this without the component's code or a reproduction scenario.
From the error, it looks pretty applicative since `jest-dom` claims the element is indeed in the document.
Can you please try to reproduce this one in codesandbox?

Thanks.

**Comment by eps1lon** [comment] 2022-08-09 13:12
Closing since no repro was provided

**Closed by eps1lon** 2022-08-09 13:12 UTC
Labels: needs more information
